package com.stablebridge.txinvestigation.domain.service;

import com.stablebridge.txinvestigation.domain.model.Finding;
import com.stablebridge.txinvestigation.domain.model.InvestigationReport;
import com.stablebridge.txinvestigation.domain.model.InvestigationSeverity;
import com.stablebridge.txinvestigation.domain.model.PaymentState;
import com.stablebridge.txinvestigation.domain.model.TimelineEvent;
import org.springframework.stereotype.Service;

import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.List;

import static com.stablebridge.txinvestigation.domain.model.InvestigationSeverity.CRITICAL;
import static com.stablebridge.txinvestigation.domain.model.InvestigationSeverity.HIGH;

@Service
public class ReportFormatter {

    private static final DateTimeFormatter TIME_FMT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss 'UTC'").withZone(ZoneOffset.UTC);

    public String format(InvestigationReport report, PaymentState payment) {
        var sb = new StringBuilder();
        sb.append("## Investigation Report: %s\n\n".formatted(payment.paymentId()));
        sb.append("**Status:** %s | **Severity:** %s\n\n".formatted(
                payment.status(), report.severity()));

        sb.append("### Root Cause\n%s\n\n".formatted(report.rootCause()));

        if (!report.timeline().isEmpty()) {
            sb.append(formatTimeline(report.timeline()));
            sb.append("\n");
        }

        if (!report.findings().isEmpty()) {
            sb.append(formatFindings(report.findings()));
            sb.append("\n");
        }

        appendRecommendations(sb, report);

        sb.append("---\n*Generated by TX Investigation Agent (Embabel + Spring AI)*");
        return sb.toString();
    }

    public String formatTimeline(List<TimelineEvent> events) {
        var sb = new StringBuilder();
        sb.append("### Timeline\n");
        sb.append("| Time | Service | Event | Status |\n");
        sb.append("|------|---------|-------|--------|\n");
        for (var event : events) {
            sb.append("| %s | %s | %s | %s |\n".formatted(
                    TIME_FMT.format(event.timestamp()),
                    event.service(),
                    event.description(),
                    event.status()));
        }
        return sb.toString();
    }

    public String formatFindings(List<Finding> findings) {
        var sb = new StringBuilder();
        sb.append("### Findings\n");
        for (var finding : findings) {
            sb.append("- %s **[%s]** %s\n".formatted(
                    severityBadge(finding.severity()),
                    finding.category(),
                    finding.description()));
        }
        return sb.toString();
    }

    private void appendRecommendations(StringBuilder sb, InvestigationReport report) {
        if (report.recommendation() == null || report.recommendation().isBlank()) {
            return;
        }
        sb.append("### Recommendation\n");
        sb.append(report.recommendation());
        sb.append("\n\n");
    }

    private String severityBadge(InvestigationSeverity severity) {
        if (severity == CRITICAL) {
            return "[CRITICAL]";
        }
        if (severity == HIGH) {
            return "[HIGH]";
        }
        return "[%s]".formatted(severity);
    }
}
